Local:
  Dir: "/root/backups/" # 本地备份目录, 绝对路径, 必须指定 
  MaxFileNum: 10

Gitea:
  WorkDir: "/root/gitea/" # Gitea 工作目录, 绝对路径, 必须指定
  BinPath: "/root/gitea/gitea" # Gitea 可执行文件路径, 绝对路径, 必须指定
  Cron: "0 0 * * *" # Gitea 备份定时任务, Ex: 每天凌晨 0 点

Cos:
  Region: ap-hongkong
  Bucket: example-1000000000
  Secret:
    ID: SecretID
    Key: SecretKey
  Path: /backup/
  MaxFileNum: 10